import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const source = await readFile(new URL('../src/app.js', import.meta.url), 'utf8');
const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const styles = await readFile(new URL('../styles.css', import.meta.url), 'utf8');

assert.match(
  source,
  /openProjectEntry\(button\.dataset\.fileId,\s*\{\s*showLoading:\s*false,\s*preserveMode:\s*true\s*\}\)/,
);

assert.match(html, /rel="icon" href="assets\/app-icon\.svg"/);
assert.match(html, /src="assets\/app-icon\.svg"/);
assert.match(source, /if \(!options\.preserveMode\) \{\s*setMode\('split'\);\s*\}/);
assert.match(html, /id="diagramViewer"/);
assert.match(source, /openDiagramViewer/);
assert.match(source, /closeDiagramViewer/);
assert.match(source, /closest\('\.diagram-flowchart'\)/);
assert.match(source, /event\.key === 'Escape'/);
assert.match(html, /id="diagramZoomOut"/);
assert.match(html, /id="diagramZoomIn"/);
assert.match(html, /id="diagramZoomReset"/);
assert.match(html, /id="diagramZoomLevel"/);
assert.match(source, /setDiagramZoom/);
assert.match(source, /zoomDiagram/);
assert.match(source, /elements\.preview\.addEventListener\('wheel'/);
assert.match(source, /diagramViewerCanvas\.addEventListener\('wheel'/);
assert.match(source, /handleDiagramWheel/);
assert.match(source, /event\.ctrlKey \|\| event\.metaKey/);
assert.match(source, /requestAnimationFrame/);
assert.match(source, /applyDiagramZoom/);
assert.match(source, /fitDiagramsToContainers/);
assert.match(source, /fitDiagramToContainer/);
assert.match(source, /centerDiagramScroll/);
assert.match(source, /window\.addEventListener\('resize', fitDiagramsToContainers\)/);
assert.match(source, /syncNativeTheme\(\)/);
assert.match(source, /markdownNative\?\.setTheme\?\.\(state\.theme\)/);
assert.match(source, /previewPane:\s*document\.querySelector\('\.preview-pane'\)/);
assert.match(source, /elements\.previewPane\.addEventListener\('scroll', syncEditorScrollToPreview,\s*\{\s*passive:\s*true\s*\}\)/);
assert.match(source, /elements\.editor\.addEventListener\('scroll', syncPreviewScrollToEditor,\s*\{\s*passive:\s*true\s*\}\)/);
assert.match(source, /render\(\{\s*scrollToSearchMatch:\s*true\s*\}\)/);
assert.match(source, /function render\(\{\s*scrollToSearchMatch = false\s*\} = \{\}\)/);
assert.match(source, /function scrollToSearchMatchElement\(\)/);
assert.match(source, /elements\.preview\.querySelector\('mark'\)/);
assert.match(source, /match\.scrollIntoView\(\{\s*behavior:\s*'smooth',\s*block:\s*'center'/);
assert.match(source, /function syncEditorScrollToPreview\(\)/);
assert.match(source, /function syncPreviewScrollToEditor\(\)/);
assert.match(source, /function syncScrollPosition\(source, target\)/);
assert.match(source, /if \(state\.mode !== 'split' \|\| state\.syncingScroll\) return/);
assert.match(source, /target\.scrollTop = ratio \* maxTargetScroll/);
assert.match(source, /syncingScroll:\s*false/);
assert.match(source, /--diagram-zoom/);
assert.match(source, /defaultScanExtensions = \['\.md'\]/);
assert.match(source, /defaultIgnoredDirectories = \['node_modules'\]/);
assert.match(source, /defaultGeneralRuleOptions/);
assert.match(source, /ignoreDotDirectories:\s*true/);
assert.match(html, /<div class="toolbar"[\s\S]*id="scanSettingsButton"[\s\S]*id="sampleButton"/);
assert.doesNotMatch(html, /pane-actions[\s\S]*scanSettingsButton/);
assert.match(html, /id="scanSettingsButton"/);
assert.match(html, /id="scanSettingsDialog"/);
assert.match(html, /id="scanSettingsClose"/);
assert.match(html, /id="scanSettingsApply"/);
assert.match(html, /id="scanExtensionInput"/);
assert.match(html, /id="generalRuleInput"/);
assert.match(html, /id="ignoreDirectoryInput"/);
assert.match(html, /id="generalRuleList"/);
assert.doesNotMatch(html, /data-scan-extension="\.markdown" checked/);
assert.doesNotMatch(html, /data-scan-extension="\.txt" checked/);
assert.match(source, /defaultScanExtensionOptions = \['\.md', '\.markdown', '\.txt'\]/);
assert.match(source, /defaultIgnoredDirectoryOptions = \['node_modules', 'dist', 'build', 'coverage', 'out'\]/);
assert.match(source, /data-ignore-dir/);
assert.match(source, /data-scan-extension/);
assert.match(source, /data-general-rule/);
assert.match(source, /openScanSettingsDialog/);
assert.match(source, /closeScanSettingsDialog/);
assert.match(source, /addScanExtension/);
assert.match(source, /addGeneralRule/);
assert.match(source, /addIgnoredDirectory/);
assert.match(source, /removeScanOption/);
assert.match(source, /data-scan-remove/);
assert.match(source, /ignoredDirectoryPatterns/);
assert.match(source, /expandedOutlineIds:\s*new Set\(\)/);
assert.match(source, /collapsedOutlineIds:\s*new Set\(\)/);
assert.match(source, /function buildOutlineEntries\(headings\)/);
assert.match(source, /function isOutlineEntryCollapsed\(entry\)/);
assert.match(source, /function toggleOutlineEntry\(outlineId\)/);
assert.match(source, /data-outline-toggle/);
assert.match(source, /data-outline-id/);
assert.match(source, /data-target="\$\{escapeHtml\(entry\.id\)\}"/);
assert.match(source, /data-heading-index="\$\{entry\.headingIndex\}"/);
assert.match(source, /data-line-index="\$\{entry\.lineIndex\}"/);
assert.match(source, /function scrollToOutlineTarget\(entry\)/);
assert.match(source, /elements\.preview\.querySelector\(`\[data-heading-index="\$\{entry\.dataset\.headingIndex\}"\]`\)/);
assert.match(source, /function scrollPreviewToHeading\(target\)/);
assert.match(source, /elements\.previewPane\.scrollTo\(\{\s*top,\s*behavior:\s*'smooth'\s*\}\)/);
assert.match(source, /function scrollEditorToLine\(lineIndex\)/);
assert.match(source, /elements\.editor\.scrollTo\(\{\s*top,\s*behavior:\s*'smooth'\s*\}\)/);
assert.match(source, /setTimeout\(\(\) => \{\s*state\.syncingScroll = false;\s*\}, 520\)/);
assert.match(source, /elements\.outline\.querySelectorAll\('\.outline-entry:not\(\.is-hidden\)'\)/);
assert.match(source, /renderOutline\(\);/);
assert.doesNotMatch(source, /toggleOutlineEntry[\s\S]*render\(\);[\s\S]*function renderStats/);
assert.match(source, /outline-entry/);
assert.match(source, /projectPanel:\s*document\.querySelector\('\.project-panel'\)/);
assert.match(source, /outlinePane:\s*document\.querySelector\('\.outline-pane'\)/);
assert.match(source, /projectPanel\.classList\.toggle\('is-hidden'/);
assert.match(source, /outlinePane\.classList\.toggle\('without-project'/);
assert.match(styles, /\.project-panel\.is-hidden/);
assert.match(styles, /\.outline-pane\.without-project/);
assert.match(styles, /\.outline-entry\.is-hidden/);
assert.match(styles, /\.outline-toggle/);
assert.match(styles, /font-size:\s*16px/);
assert.match(styles, /width:\s*30px/);
assert.match(styles, /\.outline-label/);
assert.match(styles, /\.topbar\s*\{[\s\S]*-webkit-app-region:\s*drag/);
assert.match(styles, /\.topbar button,[\s\S]*-webkit-app-region:\s*no-drag/);
assert.doesNotMatch(styles, /transition:\s*width 120ms ease,\s*min-width 120ms ease/);

console.log('app source tests passed');
