import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const source = await readFile(new URL('../src/app.js', import.meta.url), 'utf8');
const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const styles = await readFile(new URL('../styles.css', import.meta.url), 'utf8');
const toggleOutlineEntrySource = source.match(/function toggleOutlineEntry\(outlineId\)[\s\S]*?\n\}/)?.[0] || '';

assert.match(
  source,
  /openProjectEntry\(button\.dataset\.fileId,\s*\{\s*showLoading:\s*false,\s*preserveMode:\s*true\s*\}\)/,
);

assert.match(html, /rel="icon" href="assets\/app-icon\.svg"/);
assert.match(html, /src="assets\/app-icon\.svg"/);
assert.match(source, /if \(!options\.preserveMode\) \{\s*setMode\('split'\);\s*\}/);
assert.match(html, /id="diagramViewer"/);
assert.match(source, /openDiagramViewer/);
assert.match(source, /closeDiagramViewer/);
assert.match(source, /closest\('\.diagram-flowchart'\)/);
assert.match(source, /event\.key === 'Escape'/);
assert.match(html, /id="diagramZoomOut"/);
assert.match(html, /id="diagramZoomIn"/);
assert.match(html, /id="diagramZoomReset"/);
assert.match(html, /id="diagramZoomLevel"/);
assert.match(source, /setDiagramZoom/);
assert.match(source, /zoomDiagram/);
assert.match(source, /elements\.preview\.addEventListener\('wheel'/);
assert.match(source, /diagramViewerCanvas\.addEventListener\('wheel'/);
assert.match(source, /handleDiagramWheel/);
assert.match(source, /event\.ctrlKey \|\| event\.metaKey/);
assert.match(source, /requestAnimationFrame/);
assert.match(source, /applyDiagramZoom/);
assert.match(source, /fitDiagramsToContainers/);
assert.match(source, /fitDiagramToContainer/);
assert.match(source, /centerDiagramScroll/);
assert.match(source, /window\.addEventListener\('resize', fitDiagramsToContainers\)/);
assert.match(source, /syncNativeTheme\(\)/);
assert.match(source, /markdownNative\?\.setTheme\?\.\(state\.theme\)/);
assert.match(source, /previewPane:\s*document\.querySelector\('\.preview-pane'\)/);
assert.match(source, /elements\.previewPane\.addEventListener\('scroll', \(\) => \{\s*syncEditorScrollToPreview\(\);\s*updateActiveOutlineFromScroll\(\);\s*\},\s*\{\s*passive:\s*true\s*\}\)/);
assert.match(source, /elements\.editor\.addEventListener\('scroll', syncPreviewScrollToEditor,\s*\{\s*passive:\s*true\s*\}\)/);
assert.match(source, /render\(\{\s*scrollToSearchMatch:\s*true\s*\}\)/);
assert.match(source, /function render\(\{\s*scrollToSearchMatch = false,\s*focusEditorMatch = false\s*\} = \{\}\)/);
assert.match(source, /function scrollToSearchMatchElement\(\{\s*focusEditorMatch = false\s*\} = \{\}\)/);
assert.match(source, /function collectSearchMatches\(markdown = '', query = ''\)/);
assert.match(source, /function runNativeFindInPage\(\{\s*forward = true,\s*findNext = false\s*\} = \{\}\)/);
assert.match(source, /window\.markdownNative\?\.findInPage/);
assert.match(source, /window\.markdownNative\.stopFindInPage\?\.\(\)/);
assert.match(source, /elements\.preview\.innerHTML = useNativeFind \? rendered : highlightSearch\(rendered, state\.query\)/);
assert.match(source, /function selectCurrentEditorMatch/);
assert.match(source, /elements\.editor\.setSelectionRange\(match\.start, match\.end\)/);
assert.match(source, /if \(focusEditorMatch\) \{\s*elements\.editor\.setSelectionRange\(match\.start, match\.end\);\s*elements\.editor\.focus\(\{ preventScroll: true \}\);/);
assert.match(source, /previewMatch\.scrollIntoView\(\{\s*behavior:\s*'smooth',\s*block:\s*'center'/);
assert.match(source, /function stepSearchMatch\(delta,\s*\{\s*focusEditorMatch = false\s*\} = \{\}\)/);
assert.match(source, /elements\.searchInput\.addEventListener\('keydown'/);
assert.match(source, /if \(event\.key !== 'Enter'\) return/);
assert.match(source, /stepSearchMatch\(event\.shiftKey \? -1 : 1\)/);
assert.match(source, /function replaceCurrentMatch\(\)/);
assert.match(source, /function replaceAllMatches\(\)/);
assert.match(source, /state\.markdown\.replace\(matcher, state\.replaceText\)/);
assert.match(source, /recentFilesKey/);
assert.match(source, /recentProjectsKey/);
assert.match(source, /dirty:\s*false/);
assert.match(source, /currentNativePath:\s*''/);
assert.match(source, /function confirmDiscardChanges/);
assert.match(source, /window\.addEventListener\('beforeunload'/);
assert.match(source, /function saveCurrentDocument/);
assert.match(source, /function saveCurrentDocumentAs/);
assert.match(source, /markdownNative\?\.saveFile/);
assert.match(source, /markdownNative\?\.saveFileAs/);
assert.match(source, /event\.key\.toLowerCase\(\) === 's'/);
assert.match(source, /event\.shiftKey[\s\S]*saveCurrentDocumentAs\(\)/);
assert.match(source, /saveCurrentDocument\(\)/);
assert.match(source, /function rememberRecentFile/);
assert.match(source, /function renderRecentPanel/);
assert.match(source, /function openRecentFile/);
assert.match(source, /function rememberRecentProject/);
assert.match(source, /function openRecentProject/);
assert.match(source, /function renderProjectSearchResults/);
assert.match(source, /function openProjectSearchResult/);
assert.match(source, /function renderQuickOpenResults/);
assert.match(source, /function openQuickOpenResult/);
assert.match(source, /function renderDocumentRelations/);
assert.match(source, /buildProjectKnowledge/);
assert.match(source, /function hydrateProjectEntries/);
assert.match(source, /function openMarkdownLink/);
assert.match(source, /function insertImageAssetFromFile/);
assert.match(source, /markdownNative\?\.saveImageAsset/);
assert.match(source, /closest\('a'\)/);
assert.match(source, /function setFocusMode/);
assert.match(source, /function insertMarkdownSnippet/);
assert.match(source, /function insertImageFile/);
assert.match(source, /data-format-action/);
assert.match(source, /activeOutlineId:\s*''/);
assert.match(source, /function updateActiveOutlineFromScroll/);
assert.match(source, /outline-entry\$\{activeClass\}/);
assert.match(source, /function syncEditorScrollToPreview\(\)/);
assert.match(source, /function syncPreviewScrollToEditor\(\)/);
assert.match(source, /function syncScrollPosition\(source, target\)/);
assert.match(source, /if \(state\.mode !== 'split' \|\| state\.syncingScroll\) return/);
assert.match(source, /target\.scrollTop = ratio \* maxTargetScroll/);
assert.match(source, /syncingScroll:\s*false/);
assert.match(source, /--diagram-zoom/);
assert.match(source, /defaultScanExtensions = \['\.md'\]/);
assert.match(source, /defaultIgnoredDirectories = \['node_modules'\]/);
assert.match(source, /defaultGeneralRuleOptions/);
assert.match(source, /ignoreDotDirectories:\s*true/);
assert.match(html, /<div class="toolbar"[\s\S]*id="scanSettingsButton"[\s\S]*id="sampleButton"/);
assert.doesNotMatch(html, /pane-actions[\s\S]*scanSettingsButton/);
assert.match(html, /id="scanSettingsButton"/);
assert.match(html, /id="replaceInput"/);
assert.match(html, /id="searchPrevButton"/);
assert.match(html, /id="searchNextButton"/);
assert.match(html, /id="replaceButton"/);
assert.match(html, /id="replaceAllButton"/);
assert.match(html, /id="matchStatus"/);
assert.match(html, /id="saveButton"/);
assert.match(html, /id="saveAsButton"/);
assert.match(html, /id="recentButton"/);
assert.match(html, /id="recentPanel"/);
assert.match(html, /id="recentFiles"/);
assert.match(html, /id="recentProjects"/);
assert.match(html, /id="projectSearchInput"/);
assert.match(html, /id="projectSearchResults"/);
assert.match(html, /id="quickOpenInput"/);
assert.match(html, /id="quickOpenResults"/);
assert.match(html, /id="documentRelations"/);
assert.match(html, /id="focusButton"/);
assert.match(html, /id="imageInput"/);
assert.doesNotMatch(html, /id="editorSearchHighlight"/);
assert.match(html, /<textarea id="editor" spellcheck="false" wrap="off"/);
assert.match(html, /id="scanSettingsDialog"/);
assert.match(html, /id="scanSettingsClose"/);
assert.match(html, /id="scanSettingsApply"/);
assert.match(html, /id="scanExtensionInput"/);
assert.match(html, /id="generalRuleInput"/);
assert.match(html, /id="ignoreDirectoryInput"/);
assert.match(html, /id="generalRuleList"/);
assert.doesNotMatch(html, /data-scan-extension="\.markdown" checked/);
assert.doesNotMatch(html, /data-scan-extension="\.txt" checked/);
assert.match(source, /defaultScanExtensionOptions = \['\.md', '\.markdown', '\.txt'\]/);
assert.match(source, /defaultIgnoredDirectoryOptions = \['node_modules', 'dist', 'build', 'coverage', 'out'\]/);
assert.match(source, /data-ignore-dir/);
assert.match(source, /data-scan-extension/);
assert.match(source, /data-general-rule/);
assert.match(source, /openScanSettingsDialog/);
assert.match(source, /closeScanSettingsDialog/);
assert.match(source, /addScanExtension/);
assert.match(source, /addGeneralRule/);
assert.match(source, /addIgnoredDirectory/);
assert.match(source, /removeScanOption/);
assert.match(source, /data-scan-remove/);
assert.match(source, /ignoredDirectoryPatterns/);
assert.match(source, /expandedOutlineIds:\s*new Set\(\)/);
assert.match(source, /collapsedOutlineIds:\s*new Set\(\)/);
assert.match(source, /function buildOutlineEntries\(headings\)/);
assert.match(source, /function isOutlineEntryCollapsed\(entry\)/);
assert.match(source, /function toggleOutlineEntry\(outlineId\)/);
assert.match(source, /data-outline-toggle/);
assert.match(source, /data-outline-id/);
assert.match(source, /data-target="\$\{escapeHtml\(entry\.id\)\}"/);
assert.match(source, /data-heading-index="\$\{entry\.headingIndex\}"/);
assert.match(source, /data-line-index="\$\{entry\.lineIndex\}"/);
assert.match(source, /function scrollToOutlineTarget\(entry\)/);
assert.match(source, /elements\.preview\.querySelector\(`\[data-heading-index="\$\{entry\.dataset\.headingIndex\}"\]`\)/);
assert.match(source, /function scrollPreviewToHeading\(target\)/);
assert.match(source, /elements\.previewPane\.scrollTo\(\{\s*top,\s*behavior:\s*'smooth'\s*\}\)/);
assert.match(source, /function scrollEditorToLine\(lineIndex\)/);
assert.match(source, /elements\.editor\.scrollTo\(\{\s*top,\s*behavior:\s*'smooth'\s*\}\)/);
assert.match(source, /setTimeout\(\(\) => \{\s*state\.syncingScroll = false;\s*\}, 520\)/);
assert.match(source, /elements\.outline\.querySelectorAll\('\.outline-entry:not\(\.is-hidden\)'\)/);
assert.match(source, /renderOutline\(\);/);
assert.match(source, /function toggleOutlineEntry\(outlineId\)[\s\S]*renderOutline\(\);\s*\}/);
assert.doesNotMatch(toggleOutlineEntrySource, /render\(\);/);
assert.match(source, /outline-entry/);
assert.match(source, /projectPanel:\s*document\.querySelector\('\.project-panel'\)/);
assert.match(source, /outlinePane:\s*document\.querySelector\('\.outline-pane'\)/);
assert.match(source, /projectPanel\.classList\.toggle\('is-hidden'/);
assert.match(source, /outlinePane\.classList\.toggle\('without-project'/);
assert.match(styles, /\.project-panel\.is-hidden/);
assert.match(styles, /\.outline-pane\.without-project/);
assert.match(styles, /\.outline-entry\.is-hidden/);
assert.match(styles, /\.outline-toggle/);
assert.match(styles, /font-size:\s*16px/);
assert.match(styles, /width:\s*30px/);
assert.match(styles, /\.outline-label/);
assert.match(styles, /\.search-panel/);
assert.match(styles, /\.recent-panel/);
assert.match(styles, /\.project-search/);
assert.match(styles, /\.format-toolbar/);
assert.match(styles, /body\.is-focus-mode/);
assert.match(styles, /\.outline-entry\.is-active/);
assert.match(styles, /\.match-status/);
assert.doesNotMatch(styles, /\.editor-search-highlight/);
assert.match(styles, /white-space:\s*pre/);
assert.match(styles, /overflow-wrap:\s*normal/);
assert.match(styles, /mark\.is-current-search/);
assert.match(styles, /\.topbar\s*\{[\s\S]*-webkit-app-region:\s*drag/);
assert.match(styles, /\.topbar button,[\s\S]*-webkit-app-region:\s*no-drag/);
assert.doesNotMatch(styles, /transition:\s*width 120ms ease,\s*min-width 120ms ease/);

console.log('app source tests passed');
