import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const main = await readFile(new URL('../electron/main.cjs', import.meta.url), 'utf8');
const preload = await readFile(new URL('../electron/preload.cjs', import.meta.url), 'utf8');
const app = await readFile(new URL('../src/app.js', import.meta.url), 'utf8');
const manifest = await readFile(new URL('../package.json', import.meta.url), 'utf8');
const pruneWin = await readFile(new URL('../scripts/prune-win-package.cjs', import.meta.url), 'utf8');
const pruneMac = await readFile(new URL('../scripts/prune-mac-package.cjs', import.meta.url), 'utf8');
const dmgMac = await readFile(new URL('../scripts/dmg-mac-package.cjs', import.meta.url), 'utf8');
const zipMac = await readFile(new URL('../scripts/zip-mac-package.cjs', import.meta.url), 'utf8');
const zipWin = await readFile(new URL('../scripts/zip-win-package.cjs', import.meta.url), 'utf8');
const generateIcons = await readFile(new URL('../scripts/generate-icon-assets.cjs', import.meta.url), 'utf8');
const macInfo = await readFile(new URL('../electron/mac-info.plist', import.meta.url), 'utf8');

assert.match(main, /new BrowserWindow/);
assert.match(main, /\{\s*app,\s*BrowserWindow,\s*dialog,\s*ipcMain,\s*Menu\s*\}/);
assert.match(main, /mainWindow\.on\('closed'/);
assert.match(main, /mainWindow = null/);
assert.match(main, /Menu\.setApplicationMenu\(null\)/);
assert.match(main, /titleBarStyle:\s*isWindows\s*\?\s*'hidden'\s*:\s*'default'/);
assert.match(main, /titleBarOverlay:\s*isWindows\s*\?\s*getTitleBarOverlay\('light'\)\s*:\s*false/);
assert.match(main, /icon:\s*path\.join\(__dirname,\s*'\.\.',\s*'assets',\s*'app-icon\.png'\)/);
assert.match(main, /ipcMain\.handle\('native:set-theme'/);
assert.match(main, /setTitleBarOverlay/);
assert.match(main, /setBackgroundColor/);
assert.match(main, /webContents\.on\('found-in-page'/);
assert.match(main, /webContents\.send\('native:found-in-page', result\)/);
assert.match(main, /ipcMain\.handle\('native:find-in-page'/);
assert.match(main, /findInPage\(term/);
assert.match(main, /stopFindInPage\('clearSelection'\)/);
assert.doesNotMatch(main, /label:\s*'文件'/);
assert.doesNotMatch(main, /label:\s*'编辑'/);
assert.doesNotMatch(main, /label:\s*'视图'/);
assert.doesNotMatch(main, /label:\s*'窗口'/);
assert.doesNotMatch(main, /label:\s*'帮助'/);
assert.doesNotMatch(main, /label:\s*'使用说明'/);
assert.match(main, /preload:\s*path\.join\(__dirname,\s*'preload\.cjs'\)/);
assert.match(main, /ipcMain\.handle\('native:open-file'/);
assert.match(main, /ipcMain\.handle\('native:open-recent-file'/);
assert.match(main, /ipcMain\.handle\('native:open-recent-project'/);
assert.match(main, /ipcMain\.handle\('native:save-file'/);
assert.match(main, /ipcMain\.handle\('native:save-file-as'/);
assert.match(main, /ipcMain\.handle\('native:save-image-asset'/);
assert.match(main, /sanitizeAssetFileName/);
assert.match(main, /fs\.writeFile\(filePath,\s*content,\s*'utf8'\)/);
assert.match(main, /ipcMain\.handle\('native:open-project'/);
assert.match(main, /ipcMain\.handle\('native:rescan-project'/);
assert.match(main, /scanMarkdownProject/);
assert.match(main, /requestSingleInstanceLock/);
assert.match(main, /app\.on\('second-instance'/);
assert.match(main, /findMarkdownArgument\(process\.argv\)/);
assert.match(main, /function findMarkdownArgument\(args = \[\]\)/);
assert.match(main, /\\\.\(md\|markdown\)\$/);
assert.match(main, /app\.on\('open-file'/);
assert.match(main, /openMarkdownFileFromPath\(filePath\)/);
assert.match(main, /mainWindow\.webContents\.send\('native:file-opened', file\)/);
assert.match(main, /function ensureWindowForPendingFile\(\)/);
assert.match(main, /if \(app\.isReady\(\)\) createWindow\(\)/);
assert.match(main, /ipcMain\.handle\('native:consume-pending-file'/);
assert.match(main, /consumePendingMarkdownFile/);
assert.match(main, /function readMarkdownFile\(filePath\)/);
assert.match(main, /ignoredDirectoryNames/);
assert.match(main, /defaultMarkdownExtensions = \['\.md'\]/);
assert.match(main, /defaultIgnoredDirectoryNames = \['node_modules'\]/);
assert.match(main, /ignoreDotDirectories/);
assert.match(main, /ignoredDirectoryPatterns/);

assert.match(preload, /contextBridge\.exposeInMainWorld\('markdownNative'/);
assert.match(preload, /openFile/);
assert.match(preload, /openRecentFile/);
assert.match(preload, /openRecentProject/);
assert.match(preload, /saveFile/);
assert.match(preload, /saveFileAs/);
assert.match(preload, /saveImageAsset/);
assert.match(preload, /onFileOpened/);
assert.match(preload, /consumePendingFile/);
assert.match(preload, /ipcRenderer\.invoke\('native:consume-pending-file'\)/);
assert.match(preload, /ipcRenderer\.on\('native:file-opened'/);
assert.match(preload, /openProject/);
assert.match(preload, /rescanProject/);
assert.match(preload, /setTheme/);
assert.match(preload, /findInPage/);
assert.match(preload, /stopFindInPage/);
assert.match(preload, /onFoundInPage/);
assert.match(preload, /ipcRenderer\.on\('native:found-in-page'/);

assert.match(app, /window\.markdownNative/);
assert.match(app, /openNativeFile/);
assert.match(app, /openRecentFile/);
assert.match(app, /openRecentProject/);
assert.match(app, /saveCurrentDocument/);
assert.match(app, /saveCurrentDocumentAs/);
assert.match(app, /markdownNative\?\.onFileOpened/);
assert.match(app, /consumePendingNativeFile\(\)/);
assert.match(app, /markdownNative\?\.consumePendingFile/);
assert.match(app, /loadNativeMarkdownFile\(file\)/);
assert.match(app, /openNativeProject/);
assert.match(app, /rescanNativeProject/);
assert.match(app, /syncNativeTheme/);
assert.match(app, /markdownNative\?\.setTheme\?\.\(state\.theme\)/);
assert.match(app, /entry\.content/);

const packageJson = JSON.parse(manifest);
assert.equal(packageJson.main, 'electron/main.cjs');
assert.equal(packageJson.scripts.app, 'electron .');
assert.equal(packageJson.scripts.icons, 'node scripts/generate-icon-assets.cjs');
assert.match(packageJson.scripts['package:mac'], /--platform=darwin/);
assert.match(packageJson.scripts['package:mac'], /--extend-info=electron\/mac-info\.plist/);
assert.match(packageJson.scripts['package:mac'], /--icon=assets\/app-icon\.icns/);
assert.match(packageJson.scripts['package:mac'], /--quiet/);
assert.match(packageJson.scripts['package:mac'], /--ignore='\^\/\.codegraph'/);
assert.match(packageJson.scripts['package:mac'], /scripts\/prune-mac-package\.cjs/);
assert.match(packageJson.scripts['package:win'], /--platform=win32/);
assert.match(packageJson.scripts['package:win'], /--arch=x64/);
assert.match(packageJson.scripts['package:win'], /--icon=assets\/app-icon\.ico/);
assert.match(packageJson.scripts['package:win'], /--ignore='\^\/\.codegraph'/);
assert.match(packageJson.scripts['package:win'], /scripts\/prune-win-package\.cjs/);
assert.equal(packageJson.scripts['dmg:mac'], 'npm run package:mac && node scripts/dmg-mac-package.cjs');
assert.equal(packageJson.scripts['zip:mac'], 'npm run package:mac && node scripts/zip-mac-package.cjs');
assert.equal(packageJson.scripts['zip:win'], 'npm run package:win && node scripts/zip-win-package.cjs');
assert.ok(packageJson.devDependencies.electron);

assert.match(dmgMac, /Local Markdown Studio-macOS\.dmg/);
assert.match(dmgMac, /hdiutil/);
assert.match(dmgMac, /run\('ditto', \[appPath, stagedAppPath\]\)/);
assert.match(dmgMac, /function verifyElectronFramework\(appBundlePath\)/);
assert.match(dmgMac, /path\.isAbsolute\(linkTarget\)/);
assert.match(dmgMac, /fs\.symlinkSync\('\/Applications'/);
assert.match(dmgMac, /const preferredPath = path\.join\(distDir, appName\)/);
assert.match(dmgMac, /fs\.rmSync\(appPath, \{ recursive: true, force: true \}\)/);
assert.match(zipMac, /Local Markdown Studio-macOS\.zip/);
assert.match(zipMac, /Run npm run package:mac first/);
assert.match(zipMac, /const preferredPath = path\.join\(distDir, appName\)/);
assert.match(zipMac, /fs\.rmSync\(appPath, \{ recursive: true, force: true \}\)/);
assert.match(zipWin, /Local Markdown Studio-win32-x64\.zip/);
assert.match(zipWin, /Run npm run package:win first/);
assert.match(zipWin, /fs\.rmSync\(packagePath, \{ recursive: true, force: true \}\)/);
assert.match(generateIcons, /app-icon\.svg/);
assert.match(generateIcons, /app-icon\.icns/);
assert.match(generateIcons, /app-icon\.ico/);
assert.match(generateIcons, /function createIco/);

assert.match(pruneWin, /register-md-association\.cmd/);
assert.match(pruneWin, /HKCU\\Software\\Classes\\\.md/);
assert.match(pruneWin, /HKCU\\Software\\Classes\\\.markdown/);
assert.match(pruneWin, /LocalMarkdownStudio\.Markdown\\shell\\open\\command/);
assert.match(pruneWin, /%%1/);
assert.match(pruneMac, /function removePackageSiblings\(rootPath, keptEntryName\)/);
assert.match(pruneMac, /if \(entry === keptEntryName\) continue/);
assert.match(pruneMac, /function moveAppToDistRoot\(sourcePath, targetPath\)/);
assert.match(pruneMac, /fs\.renameSync\(sourcePath, targetPath\)/);
assert.match(pruneMac, /fs\.rmSync\(packageDir, \{ recursive: true, force: true \}\)/);
assert.match(pruneMac, /fs\.rmSync\(path\.join\(distDir, '\.DS_Store'\), \{ force: true \}\)/);
assert.match(pruneMac, /Removed macOS package metadata outside app bundle/);

assert.match(macInfo, /CFBundleDocumentTypes/);
assert.match(macInfo, /net\.daringfireball\.markdown/);
assert.match(macInfo, /<string>md<\/string>/);
assert.match(macInfo, /<string>markdown<\/string>/);
assert.doesNotMatch(macInfo, /<string>txt<\/string>/);
assert.doesNotMatch(macInfo, /public\.plain-text/);

console.log('electron source tests passed');
