import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const website = await readFile(new URL('../website/index.html', import.meta.url), 'utf8');
const styles = await readFile(new URL('../website/styles.css', import.meta.url), 'utf8');

assert.match(website, /<title>Local Markdown Studio/);
assert.match(website, /href="\.\.\/dist\/Local Markdown Studio-macOS\.dmg"/);
assert.match(website, /M1 \/ M2 \/ M3 \/ M4/);
assert.match(website, /Intel Mac/);
assert.match(website, /Local Markdown Studio-macOS-x64\.dmg/);
assert.match(website, /xattr -dr com\.apple\.quarantine/);
assert.match(website, /本地优先/);
assert.match(website, /保存与另存为/);
assert.match(website, /最近文件/);
assert.match(website, /项目级搜索/);
assert.match(website, /图片资产管理/);
assert.match(website, /真实相对路径/);
assert.match(website, /反向链接/);
assert.match(website, /失效链接/);
assert.match(website, /快速打开/);
assert.match(website, /项目健康检查/);
assert.match(website, /一键修复/);
assert.match(website, /绝对路径图片/);
assert.match(website, /引用关系/);
assert.match(website, /扫描 → 定位 → 修复 → 导出/);
assert.match(website, /新建文档/);
assert.match(website, /新建文件夹/);
assert.match(website, /写作工具栏/);
assert.match(website, /专注模式/);
assert.match(website, /本地链接跳转/);
assert.match(website, /Cmd\/Ctrl \+ S/);
assert.match(website, /assets\/app-preview\.png/);
assert.match(website, /assets\/app-icon\.svg/);
assert.match(website, /rel="icon"/);
assert.match(website, /hero-inner/);
assert.match(website, /hero-highlights/);
assert.match(website, /section-inner/);
assert.match(styles, /--content-max: 1480px/);
assert.match(styles, /\.section-inner/);
assert.match(styles, /--accent: #3157d5/);
assert.match(styles, /@keyframes heroReveal/);
assert.match(styles, /@keyframes previewFloat/);
assert.match(styles, /@media \(max-width: 760px\)/);
assert.match(styles, /\.hero/);
assert.match(styles, /\.download-panel/);
assert.match(styles, /\.workflow-panel/);
assert.match(styles, /prefers-reduced-motion/);
assert.doesNotMatch(styles, /letter-spacing:\s*-/);

console.log('website source tests passed');
